apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payments
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yormansj97/argoCDPractice.git
    targetRevision: HEAD
    path: helm-charts/app-chart
    helm:
      valueFiles:
        - ../values-payments.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

